name: SAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  security-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------- Semgrep Scans ----------
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan (SARIF)
        run: |
          echo "Scanning all py for SARIF..."
          semgrep --config p/owasp-top-ten \
                  --config p/python \
                  --config p/secrets \
                  --verbose \
                  --sarif --output semgrep.sarif \
                  .

      - name: Run Semgrep scan (JSON)
        run: |
          echo "Scanning all for JSON..."
          semgrep --config p/owasp-top-ten \
                  --config p/python \
                  --config p/secrets \
                  --verbose \
                  --json --output semgrep.json \
                  .

      - name: Upload Semgrep SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Upload Semgrep JSON to DefectDojo
        env:
          DOJO_URL: ${{ secrets.DOJO_URL }}
          DOJO_API_KEY: ${{ secrets.DOJO_API_KEY }}
          DOJO_ENGAGEMENT_ID: ${{ secrets.DOJO_ENGAGEMENT_ID }}
        run: |
          curl -X POST "${DOJO_URL}/api/v2/import-scan/" \
            -H "Authorization: Token ${DOJO_API_KEY}" \
            -F "scan_type=Semgrep JSON Report" \
            -F "file=@semgrep.json" \
            -F "engagement=${DOJO_ENGAGEMENT_ID}" \
            -F "active=true" \
            -F "verified=false"
