      - name: Upload Semgrep JSON to DefectDojo
        env:
          DOJO_URL: ${{ secrets.DOJO_URL }}
          DOJO_API_KEY: ${{ secrets.DOJO_API_KEY }}
          DOJO_ENGAGEMENT_ID: ${{ secrets.DOJO_ENGAGEMENT_ID }}
        run: |
          curl -X POST "${DOJO_URL}/api/v2/import-scan/" \
            -H "Authorization: Token ${DOJO_API_KEY}" \
            -F "scan_type=Semgrep JSON Report" \
            -F "file=@semgrep.json" \
            -F "engagement=${DOJO_ENGAGEMENT_ID}" \
            -F "active=true" \
            -F "verified=false"

      - name: Upload CodeQL SARIF to DefectDojo
        env:
          DOJO_URL: ${{ secrets.DOJO_URL }}
          DOJO_API_KEY: ${{ secrets.DOJO_API_KEY }}
          DOJO_ENGAGEMENT_ID: ${{ secrets.DOJO_ENGAGEMENT_ID }}
        run: |
          CODEQL_SARIF=$(find codeql-results -type f -name "*.sarif" | head -n 1 || echo "")
          if [ -n "$CODEQL_SARIF" ]; then
            echo "Uploading $CODEQL_SARIF to DefectDojo..."
            curl -sS -X POST "${DOJO_URL}/api/v2/import-scan/" \
              -H "Authorization: Token ${DOJO_API_KEY}" \
              -F "scan_type=CodeQL Scan" \
              -F "file=@${CODEQL_SARIF}" \
              -F "engagement=${DOJO_ENGAGEMENT_ID}" \
              -F "active=true" \
              -F "verified=false"
          else
            echo "No SARIF files found."
          fi
