name: SAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan (SARIF)
        run: |
          echo "Scanning vuln_sample.py for SARIF..."
          semgrep --config "p/owasp-top-ten,p/python,p/secrets" \
            --verbose \
            --sarif --output semgrep.sarif \
            ./vuln_sample.py

      - name: Run Semgrep scan (JSON)
        run: |
          echo "Scanning vuln_sample.py for JSON..."
          semgrep --config "p/owasp-top-ten,p/python,p/secrets" \
            --verbose \
            --json --output semgrep.json \
            ./vuln_sample.py

      - name: Upload scan results (SARIF) to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Upload scan results (JSON) to DefectDojo
        run: |
          if [ -f "semgrep.json" ]; then
            echo "Uploading semgrep.json to DefectDojo..."
            curl -X POST "${{ secrets.DOJO_URL }}/api/v2/import-scan/" \
              -H "Authorization: Token ${{ secrets.DOJO_API_KEY }}" \
              -F "scan_type=Semgrep JSON Report" \
              -F "file=@semgrep.json" \
              -F "engagement=${{ secrets.DOJO_ENGAGEMENT_ID }}" \
              -F "active=true" \
              -F "verified=false"
          else
            echo "semgrep.json not found!"
          fi
